set(temperature_sensor_controller_MESSAGE_FILES "/root/ari_public_catkin_ws/src/ros_controllers/temperature_sensor_controller/msg/ActuatorTemperatureState.msg")
set(temperature_sensor_controller_SERVICE_FILES "")
